# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

print_it <- function(t) {
    invisible(.Call(`_CVSCIR_print_it`, t))
}

rcpp_words_idx <- function(doc) {
    .Call(`_CVSCIR_rcpp_words_idx`, doc)
}

rcpp_mat_init <- function(K, W, D) {
    .Call(`_CVSCIR_rcpp_mat_init`, K, W, D)
}

rcpp_cumprob_ini <- function(K) {
    .Call(`_CVSCIR_rcpp_cumprob_ini`, K)
}

rcpp_runif <- function(n) {
    .Call(`_CVSCIR_rcpp_runif`, n)
}

rcpp_sample_cnt <- function(alpha, probs_init, docs_list, theta, gibbs_iters, gibbs_burnin) {
    .Call(`_CVSCIR_rcpp_sample_cnt`, alpha, probs_init, docs_list, theta, gibbs_iters, gibbs_burnin)
}

sample_index <- function(P_marg_z_ij) {
    .Call(`_CVSCIR_sample_index`, P_marg_z_ij)
}

sample_index_from_joint <- function(P_joint) {
    .Call(`_CVSCIR_sample_index_from_joint`, P_joint)
}

CIR_B_update_grad_ij <- function(theta_1, theta_0, pi_i, pi_j, Y_ij) {
    .Call(`_CVSCIR_CIR_B_update_grad_ij`, theta_1, theta_0, pi_i, pi_j, Y_ij)
}

CIR_B_update_no_par <- function(theta_1, theta_0, pi, Y, subE) {
    .Call(`_CVSCIR_CIR_B_update_no_par`, theta_1, theta_0, pi, Y, subE)
}

CIR_pi_update_grad_i <- function(i, B, phi, Y_i_r, Y_i_c, subV_i) {
    .Call(`_CVSCIR_CIR_pi_update_grad_i`, i, B, phi, Y_i_r, Y_i_c, subV_i)
}

CIR_pi_update_no_par <- function(B, phi, Y, sub_V_xi, sub_V_i_list) {
    .Call(`_CVSCIR_CIR_pi_update_no_par`, B, phi, Y, sub_V_xi, sub_V_i_list)
}

grad_SG_global_update_ij <- function(theta_0, theta_1, B, pi_i, pi_j, Y_ij) {
    .Call(`_CVSCIR_grad_SG_global_update_ij`, theta_0, theta_1, B, pi_i, pi_j, Y_ij)
}

SG_B_update_no_par <- function(theta_0, theta_1, B, pi, Y, subE) {
    .Call(`_CVSCIR_SG_B_update_no_par`, theta_0, theta_1, B, pi, Y, subE)
}

grad_SG_local_update_i <- function(i, phi_i, B, pi, Y_i_p, Y_p_i, subV_i) {
    .Call(`_CVSCIR_grad_SG_local_update_i`, i, phi_i, B, pi, Y_i_p, Y_p_i, subV_i)
}

SG_pi_update_no_par <- function(phi, B, pi, Y, V_all, sub_V_xi) {
    .Call(`_CVSCIR_SG_pi_update_no_par`, phi, B, pi, Y, V_all, sub_V_xi)
}

P_0_fun <- function(Y, pi_0, B_0) {
    .Call(`_CVSCIR_P_0_fun`, Y, pi_0, B_0)
}

P_fun <- function(Y, pi_list, B_list) {
    .Call(`_CVSCIR_P_fun`, Y, pi_list, B_list)
}

rcpparma_hello_world <- function() {
    .Call(`_CVSCIR_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_CVSCIR_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_CVSCIR_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_CVSCIR_rcpparma_bothproducts`, x)
}

